spring:
  application:
    name: "user-service"
  cloud:
    vault:
      uri: "${VAULT_URI:http://localhost:8200}"
      token: "${VAULT_TOKEN:hvs.fI1GQCutzKi6ouX36ZbOYNyI}"
      kv:
        enabled: true
        backend: kv
  config:
    import: "vault://kv/${spring.application.name}, vault://kv/general"
  rabbitmq:
    host: "${RABBITMQ_HOST:localhost}"
    port: "${RABBITMQ_PORT:5672}"
    virtual-host: "${RABBITMQ_VHOST:rabbitmq}"
    template:
      retry:
        enabled: true
        initial-interval: 2s
server:
  port: "${SERVER_PORT:8500}"