spring:
  application:
    name: "user-service"
  datasource:
    url: "${DB_URL:jdbc:postgresql://localhost/parcelplatform}"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    vault:
      uri: "${VAULT_URI:http://localhost:8200}"
      token: "${VAULT_TOKEN:hvs.6kSyqeaKbLKv7kBHoJvHz6KR}"
      kv:
        enabled: true
        backend: kv
  config:
    import: "vault://kv/${spring.application.name}, vault://kv/general"
  rabbitmq:
    host: "${RABBITMQ_HOST:localhost}"
    port: "${RABBITMQ_PORT:5672}"
    virtual-host: "${RABBITMQ_VHOST:rabbitmq}"
    template:
      retry:
        enabled: true
        initial-interval: 2s
management:
  endpoint:
    health:
      probes:
        enabled: true   # Kubernetes readiness and liveness probes
        add-additional-paths: true
  endpoints:  # Metrics for Prometheus
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
server:
  port: "${SERVER_PORT:8500}"