apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.19.0
    helm:
      releaseName: external-dns
      values: |
        apiVersion: v1
        data:
          apiKey: apikey
          email: email
        kind: Secret
        metadata:
          creationTimestamp: null
          name: cloudflare-api-key
        ---       
        provider:
          name: cloudflare
        env:
          - name: CF_API_KEY
            valueFrom:
              secretKeyRef:
                name: cloudflare-api-key
                key: apiKey
          - name: CF_API_EMAIL
            valueFrom:
              secretKeyRef:
                name: cloudflare-api-key
                key: email
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true