apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: gateway-operator
    repoURL: https://charts.konghq.com
    targetRevision: 0.6.1
    helm:
      releaseName: kong-operator
      parameters:
        - name: env.ENABLE_CONTROLLER_KONNECT
          value: "true"
        - name: global.webhooks.options.certManager.enabled
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: kong-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true