apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
spec:
  project: default
  source:
    chart: base
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: HEAD
    helm:
      releaseName: istio-base
      parameters:
        - name: defaultRevision
          value: default
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      enable: true
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true