spring:
  application:
    name: "storage-service"
  cloud:
    aws:
      s3:
        endpoint: "${MINIO_ENDPOINT:http://localhost:9000}"
        region: "us-east-1"
    vault:
      uri: "${VAULT_URI:http://localhost:8200}"
      token: "${VAULT_TOKEN:hvs.6kSyqeaKbLKv7kBHoJvHz6KR}"
      kv:
        enabled: true
        backend: kv
  config:
    import: "vault://kv/${spring.application.name}, vault://kv/general"
  rabbitmq:
    host: "${RABBITMQ_HOST:localhost}"
    port: "${RABBITMQ_PORT:5672}"
    virtual-host: "${RABBITMQ_VHOST:rabbitmq}"
    template:
      retry:
        enabled: true
        initial-interval: 2s
management:
  endpoint:
    health:
      probes:
        enabled: true   # Kubernetes readiness and liveness probes
        add-additional-paths: true
  endpoints:  # Metrics for Prometheus
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
env:
  aws:
    bucket:
      name: "${MINIO_BUCKET:storage-service}"
server:
  port: "${SERVER_PORT:8501}"